/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'projectId' : IDL.Nat,
  'elementId' : IDL.Text,
  'position' : IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EngineeringInputs = IDL.Record({
  'windSpeed' : IDL.Nat,
  'liveLoad' : IDL.Nat,
  'seismicZone' : IDL.Text,
});
export const BrandingSettings = IDL.Record({
  'primaryColorRal' : IDL.Text,
  'signageText' : IDL.Text,
  'secondaryColorRal' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'queued' : IDL.Null,
  'processed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'engineeringInputs' : EngineeringInputs,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'uploadedFileName' : IDL.Text,
  'updatedAt' : Time,
  'erectionDataJSON' : IDL.Opt(IDL.Text),
  'brandingSettings' : BrandingSettings,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'subscriptionTier' : SubscriptionTier,
  'email' : IDL.Text,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64, 'z' : IDL.Float64 }),
        IDL.Text,
      ],
      [Comment],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, EngineeringInputs, BrandingSettings],
      [IDL.Nat],
      [],
    ),
  'createSharedLink' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getProjectByShareToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Project)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjectsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveErectionData' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setStripeCustomerId' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBrandingSettings' : IDL.Func([IDL.Nat, BrandingSettings], [], []),
  'updateEngineeringInputs' : IDL.Func([IDL.Nat, EngineeringInputs], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
  'updateSubscriptionTier' : IDL.Func(
      [IDL.Principal, SubscriptionTier],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'projectId' : IDL.Nat,
    'elementId' : IDL.Text,
    'position' : IDL.Record({
      'x' : IDL.Float64,
      'y' : IDL.Float64,
      'z' : IDL.Float64,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EngineeringInputs = IDL.Record({
    'windSpeed' : IDL.Nat,
    'liveLoad' : IDL.Nat,
    'seismicZone' : IDL.Text,
  });
  const BrandingSettings = IDL.Record({
    'primaryColorRal' : IDL.Text,
    'signageText' : IDL.Text,
    'secondaryColorRal' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'queued' : IDL.Null,
    'processed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'engineeringInputs' : EngineeringInputs,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'uploadedFileName' : IDL.Text,
    'updatedAt' : Time,
    'erectionDataJSON' : IDL.Opt(IDL.Text),
    'brandingSettings' : BrandingSettings,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscriptionTier = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'subscriptionTier' : SubscriptionTier,
    'email' : IDL.Text,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Record({
            'x' : IDL.Float64,
            'y' : IDL.Float64,
            'z' : IDL.Float64,
          }),
          IDL.Text,
        ],
        [Comment],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, EngineeringInputs, BrandingSettings],
        [IDL.Nat],
        [],
      ),
    'createSharedLink' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getProjectByShareToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Project)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjectsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveErectionData' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setStripeCustomerId' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBrandingSettings' : IDL.Func([IDL.Nat, BrandingSettings], [], []),
    'updateEngineeringInputs' : IDL.Func([IDL.Nat, EngineeringInputs], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
    'updateSubscriptionTier' : IDL.Func(
        [IDL.Principal, SubscriptionTier],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };