/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandingSettings {
  'primaryColorRal' : string,
  'signageText' : string,
  'secondaryColorRal' : string,
}
export interface EngineeringInputs {
  'windSpeed' : bigint,
  'liveLoad' : bigint,
  'seismicZone' : string,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'engineeringInputs' : EngineeringInputs,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'uploadedFileName' : string,
  'updatedAt' : Time,
  'erectionDataJSON' : [] | [string],
  'brandingSettings' : BrandingSettings,
}
export type ProjectStatus = { 'queued' : null } |
  { 'processed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'id' : Principal,
  'displayName' : string,
  'createdAt' : Time,
  'subscriptionTier' : SubscriptionTier,
  'email' : string,
  'stripeCustomerId' : [] | [string],
}
export interface UserProfile { 'displayName' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProject' : ActorMethod<
    [string, string, EngineeringInputs, BrandingSettings],
    bigint
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUser' : ActorMethod<[Principal], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listProjectsByOwner' : ActorMethod<[Principal], Array<Project>>,
  'registerUser' : ActorMethod<[string, string], User>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveErectionData' : ActorMethod<[bigint, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setStripeCustomerId' : ActorMethod<[Principal, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBrandingSettings' : ActorMethod<[bigint, BrandingSettings], undefined>,
  'updateEngineeringInputs' : ActorMethod<
    [bigint, EngineeringInputs],
    undefined
  >,
  'updateProjectStatus' : ActorMethod<[bigint, ProjectStatus], undefined>,
  'updateSubscriptionTier' : ActorMethod<
    [Principal, SubscriptionTier],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];